### ISSUE TITLE
ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by menoc61** [OVRAT/AI#2]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP ENVY\AppData\Local\Programs\Python\Python311\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP ENVY\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\HP ENVY\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "C:\Users\HP ENVY\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\elements\arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

**The app cannot start**

**Comment by menoc61** [comment]
I created this issue because i encountered it during developement on my window computer,
https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921/12

- This is the link where i lead about the issue this is because of altair which has an error with the current version of streamlit 
- To fix it juste run **pip install altair<5**
- But just to be sur i added it instead the requirement.txt file 😄 
- If you find this useful leave a star🌟
